### ISSUE TITLE
Dep installation fails on first-time vagrant up

### ISSUE THREAD

**Issue by jparavisini** [snowplow-devops/terraform-provider-snowplow#1]
Error encountered during initial `vagrant up` using vagrant_2.2.6_x86_64 and VirtualBox-6.0.14-133895-OSX

```   
default: =====================
default: INSTALLING GOLANG DEP
default: ---------------------
...
default: sh: 68: go: not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
This issue requires manually executing the `curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh` step in order to proceed with building the provider.

**Comment by jbeemster** [comment]
Yeah I had noticed that as well but had already moved to using my host for building rather than Vagrant when I was finishing up this release.

Did you want to have a crack at fixing that @jparavisini ?
